### ISSUE TITLE
Sample - platform.hpp file not found

### ISSUE THREAD

**Issue by raphaelguye** [hyperledger/aries-framework-swift#14]
Trying to run the Sample App following the [README instructions](https://github.com/hyperledger/aries-framework-swift#sample-app), I get this error message (simulator and real device):
`'platform.hpp' file not found`

<img width="550" alt="Screenshot 2022-12-21 at 09 46 34" src="https://user-images.githubusercontent.com/1267845/208860420-438a0895-e134-4efd-8d7d-6acc16f72d37.png">

Building on an Intel MacBook Pro with Xcode 14.2.

Do I forget to init / build something?

**Comment by conanoc** [comment]
I forgot to add more guides in the readme.md. You need `cmake` to build libzmq.
This will fix your issue:
- Install cmake: `brew install cmake`
- Clear cocoapods cache: `rm -r ~/Library/Caches/CocoaPods`
- Then, run `pod install` again
