### ISSUE TITLE
Is there a way to start present proof from prover side?

### ISSUE THREAD

**Issue by kukgini** [hyperledger/aries-framework-swift#42]
In [present proof 1.0 specification](https://github.com/hyperledger/aries-rfcs/blob/main/features/0037-present-proof/README.md).
It describes `alternate begining (Prover begins with proposal)` process.
Is this feature supported in AFS ?
It is necessary when prover (holder) has no mediator.

**Comment by conanoc** [comment]
No. Proposing proof is not supported. You could use oob attaching a proof-request-message.
