### ISSUE TITLE
Query: Can I use Swift UI to connect to an Aries JS local server

### ISSUE THREAD

**Issue by dnaicker86** [hyperledger/aries-framework-swift#62]
Can I use Swift UI to connect to an Aries JS local server?

**Comment by conanoc** [comment]
Yes, you can. On the simulator, use localhost for your Aries JS endpoint. On the mobile phone, you could use ngrok or you could share the WiFi of your local machine to connect to the local IP.

**Comment by dnaicker86** [comment]
> Yes, you can. On the simulator, use localhost for your Aries JS endpoint. On the mobile phone, you could use ngrok or you could share the WiFi of your local machine to connect to the local IP.

Thank you!
